# Generated by Django 3.1.2 on 2021-06-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0011_auto_20210117_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, verbose_name='логин модератора')),
                ('password', models.CharField(max_length=255, verbose_name='пароль, да я храню его в бд и что?')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='аватар')),
            ],
            options={
                'verbose_name': 'Модератор',
                'verbose_name_plural': 'Модераторы',
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
